In [18]:
s1 = "ATCGTAGCTCGACGTA"
s2 = "ACTGGCAAGCTCGTTA"
import numpy as np

In [20]:
mat = np.zeros([16,16],dtype=int)
for i in range (0,len(s1)):
    for j in range (0,len(s1)):
        try:
            if s1[i] == s2[j]:
                mat[i][j] = mat[i-1][j-1] + 5
            if s1[i] != s2[j-1]:
                a = matrix[i][j-1] -4
                b = matrix[i-1][j] -4 
                c = matrix[i-1][j-1] - 4
                mat[i][j] = max(a,b,c)
        except:
            if s1[i] == s2[j]:
                mat[i][j] = 0+5
            if s1[i] != s2[j]:
                a = 0 -4
                b = 0 -4 
                c = 0 - 4
                mat[i][j] = max(a,b,c)
print(mat)

[[ 5  0 -4 -4 -4 -4  5  5  0 -4 -4 -4 -4 -4 -4  5]
 [-4 -4  5  0 -4 -4 -4 -4 -4 -4  5  0 -4  5  1  0]
 [-4  5  0 -4 -4  5  0 -4 -4  5  0  5  0 -4 -4 -4]
 [-4 -4 -4  5  1  0 -4 -4  5  0 -4 -4  5  0 -4 -4]
 [-4 -4  5  0 -4 -4 -4 -4 -4 -4  5  0 -4  5  5  0]
 [ 5  0 -4 -4 -4 -4  5  1  0 -4 -4 -4 -4 -4 -4  5]
 [-4 -4 -4  5  1  0 -4 -4  5  0 -4 -4  5  0 -4 -4]
 [-4  5  0 -4 -4  5  0 -4 -4  5  0  5  0 -4 -4 -4]
 [-4 -4  5  0 -4 -4 -4 -4 -4 -4  5  0 -4  5  1  0]
 [-4  5  0 -4 -4  5  0 -4 -4  5  0  5  0 -4 -4 -4]
 [-4 -4 -4  5  1  0 -4 -4  5  0 -4 -4  5  0 -4 -4]
 [ 1  0 -4 -4 -4 -4  5  1  0 -4 -4 -4 -4 -4 -4  5]
 [-4  5  0 -4 -4  5  0 -4 -4  5  0  5  0 -4 -4 -4]
 [-4 -4 -4  5  1  0 -4 -4  5  0 -4 -4  5  0 -4 -4]
 [-4 -4  5  0 -4 -4 -4 -4 -4 -4  5  0 -4  5  5  0]
 [ 5  0 -4 -4 -4 -4  5  1  0 -4 -4 -4 -4 -4 -4  5]]
